import Banner from '@/components/Banner';
import Content from '@/components/Content';
import Content3Point from '@/components/Content/3Point';
import Content6Point from '@/components/Content/6Point';
import FAQ from '@/components/FAQ';
import Section from '@/components/Section';
import { sendEventTracker } from '@/utils/analytics/tracker';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';

const Home: NextPage = () => {
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta
          name="viewport"
          content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"
        />
        <meta name="description" content="Description" />
        <meta name="keywords" content="Keywords" />
        <title>Next.js PWA Example</title>

        <link rel="manifest" href="/manifest.json" />
        <link
          href="/favicon-16x16.png"
          rel="icon"
          type="image/png"
          sizes="16x16"
        />
        <link
          href="/favicon-32x32.png"
          rel="icon"
          type="image/png"
          sizes="32x32"
        />
        <link rel="apple-touch-icon" href="/apple-icon.png"></link>
        <meta name="theme-color" content="#317EFB" />
      </Head>
      <Banner />
      <Content6Point />
      <Section
        onButtonClick={() => {
          sendEventTracker({
            name: 'click',
            category: `${router.pathname} - section`,
            label: 'why joyful?',
          });
          router.push('why');
        }}
        buttonText="Cari tahu lebih lanjut!"
        description="Pakaian Anda akan dicuci terpisah dengan pakaian milik orang lain, dibersihkan sesuai dengan preferensi Anda, lalu akan dilipat rapi sampai ke tangan Anda."
        title="Kenapa Joyful ?"
      />
      <Content3Point />
      <Section
        reverse
        onButtonClick={() => {
          console.log('t');
        }}
        buttonText="Find out more"
        description="Pakaian Anda akan dicuci terpisah dengan pakaian milik orang lain, dibersihkan sesuai dengan preferensi Anda, lalu akan dilipat rapi sampai ke tangan Anda."
        title="Kenapa Joyful ?"
      />
      <Content />
      <FAQ />
    </div>
  );
};

export default Home;
